# topic-search.rq
#
# @Cache-Control: no-store
#
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX meeting: <http://localhost:8080/schema/>

SELECT ?resource ?label {
    ?resource a <Topic>; rdfs:label ?label
    {
        ?resource meeting:state <topic-state/new>
    } UNION {
        ?resource meeting:state <topic-state/open>
    }
    FILTER regex(?label, "$q")
} ORDER BY ?label LIMIT 10
